### ISSUE TITLE
maxDataPoints does not seem to be respected

### ISSUE THREAD

**Issue by kodek** [pR0Ps/grafana-trackmap-panel#14]
I've set the value to 1, and it does not have any effect on the graph. Upon looking at the code, I'm not sure "maxDataPoints" is referenced anywhere.

Unrelated: I'm still seeing a data point limit, but I'm assuming it's imposed by Grafana. Is this limit documented anywhere? Thanks!

**Comment by pR0Ps** [comment]
It's a Grafana thing: https://grafana.com/docs/plugins/developing/datasources/#query

As near as I can tell it only makes a difference when the backend supports it. Graphite [does](https://graphite.readthedocs.io/en/1.1.4/render_api.html#maxdatapoints) and there is [an issue on InfluxDB](https://github.com/influxdata/influxdb/issues/3679) to add support for it.

**Comment by pR0Ps** [comment]
Actually I'll leave this open - this limitation should be communicated to the user via a tooltip on the max data points option.

**Comment by pR0Ps** [comment]
Removed the option instead
