### ISSUE TITLE
Typo when checking timestamp

### ISSUE THREAD

**Issue by Emilien942702** [pR0Ps/grafana-trackmap-panel#15]
Hi,

I think there is a typo at this [line](https://github.com/pR0Ps/grafana-trackmap-panel/blob/bad488cb1d7a7bc3098e7453700103c797ffdf32/src/trackmap_ctrl.js#L324) : 

`if (lats[i][0] == null || lons[i][0] == null ||
          `**lats[i][1] !== lats[i][1]**`) {
        continue;
      }
`

Shouldn't it be `lats[i][1] !== lons[i][1]` instead ?(you check if lat and lon have the same timestamps)

Thank you,

**Comment by pR0Ps** [comment]
You are correct, thanks for letting me know!
