### ISSUE TITLE
Query returning results without displaying on map

### ISSUE THREAD

**Issue by jlark** [pR0Ps/grafana-trackmap-panel#17]
Apologies if this is very straightforward or I'm missing something. 

I'm running a straight forward query to retrieve GPS coordinates from our vehicles on the road. I see through the query inspector that I am indeed getting a proper response in the format of, datetime, latitute, longitude.

Though I failed to find a way to get them to appear on the map.
Query inspector data attached
**query:**
SELECT "latitude" , "longitude" FROM "position" WHERE "name"="Beta Bike 8" AND $timeFilter 
**result:**

params:Object
db:"ampersand"
q:"SELECT "latitude" , "longitude" FROM "position" WHERE ("name" =~ /^(Beta BIke 3|Beta Bike 1|Beta Bike 10|Beta Bike 11|Beta Bike 12|Beta Bike 13|Beta Bike 2|Beta Bike 4|Beta Bike 5|Beta Bike 6|Beta Bike 9|Beta Bike7|Beta Bike8)$/) AND time >= now() - 6h GROUP BY "name""
epoch:"ms"
data:null
precision:"ms"
response:Object
results:Array[1]
0:Object
statement_id:0
series:Array[9]
0:Object
name:"position"
tags:Object
name:"Beta Bike 1"
columns:Array[3]
0:"time"
1:"latitude"
2:"longitude"
values:Array[5526]
0:Array[1566879620000,-1.969145,30.087898]
1:Array[1566879620000,-1.969145,30.087898]
2:Array[1566879621000,-1.969167,30.087889]
3:Array[1566879623000,-1.969183,30.087867]
4:Array[1566879626000,-1.969217,30.087826]
5:Array[1566879628000,-1.969251,30.087786]

**Comment by reactcker** [comment]
You have to probably adjust your time range and query and also try using group by time.

`SELECT mean("latlnglist"), median("longlist") FROM "location" WHERE 'key' =~ /key/ AND  $timeFilter GROUP BY time(2s)`

![image](https://user-images.githubusercontent.com/46157295/64445100-4e40a300-d0f3-11e9-8699-8a7783123f2e.png)

**Comment by jlark** [comment]
Hi,
Thanks for the response!  Though what I don't understand is the query is actually returning a result fine when I do inspect query.  

Shouldn't that be displayed accordingly on the map? I'm not seeing anything.

0:Array[1566879620000,-1.969145,30.087898]
1:Array[1566879620000,-1.969145,30.087898]
2:Array[1566879621000,-1.969167,30.087889]
3:Array[1566879623000,-1.969183,30.087867]
4:Array[1566879626000,-1.969217,30.087826]
5:Array[1566879628000,-1.969251,30.087786]

**Comment by reactcker** [comment]
@jlark, 
I can help you and we can compare with what i have as a "working example", let me know once you are available we can connect.

**Comment by jlark** [comment]
thanks @reactcker sure what's the best way to go about this? Can find me on email atilev@gmail.com

**Comment by jlark** [comment]
solved by selecting format as 
"Time Series"

![image](https://user-images.githubusercontent.com/956722/64864193-dfa19f00-d636-11e9-98f1-a9b14866e8da.png)

**Comment by pR0Ps** [comment]
@jlark Glad you figured this out, I'll add a note to the README to make this more clear.
