### ISSUE TITLE
Unable to change map type?

### ISSUE THREAD

**Issue by proffalken** [pR0Ps/grafana-trackmap-panel#24]
Hi,

I'm running TrackMap 2.0.4 and Grafana 6.4.3.

I've got a dashboard with public information on it at https://shared.ourdata.network/d/UOGNTn5Wk/rak-7200?orgId=3&from=now-1h&to=now&refresh=30s but I'm not able to switch from OSM to the other map types.

Have I missed a setting somewhere?

I'm installing using the `grafana plugins` command, *not* via git.

**Comment by pR0Ps** [comment]
As far as I can tell, no, you haven't missed anything. It was working perfectly for me (Firefox 71.0b3).

Screenshot showing the satellite map:

![Screen Shot 2019-11-16 at 12 46 27 AM](https://user-images.githubusercontent.com/466941/68988773-958d9300-080a-11ea-8ad4-f96b69e0f700.png)

**Comment by dronefarmer** [comment]
I too am unable to change to the other map types.  Tested in Chrome 78.0.3904.97 and Firefox 70.0.1 (64-bit).  Grafana 6.4.4 and TrackMap 2.0.4.  I also installed using grafana plugins.  

When I mouse over the drop down layer selector, the OpenTopoMap and Satellite options are disabled.  I cannot click them.

**Comment by dronefarmer** [comment]
Disregard my previous comment.  The issue stemmed from zooming in too much.  Once I zoomed out the options were available.  

Sorry!

**Comment by pR0Ps** [comment]
@proffalken does zooming out fix your issue too?

**Comment by proffalken** [comment]
@pR0Ps Yup, it does, thanks - didn't even think about that!
