### ISSUE TITLE
Default Map Type Selection

### ISSUE THREAD

**Issue by KevinUrbanski** [pR0Ps/grafana-trackmap-panel#31]
Hello.

I'm working with GPS data from a part of the world that doesn't have very good openstreetmap data.  The satellite view works well here.  Ideally, every time the dashboard is loaded, it'd be really nice not to have to set the maps to use the satellite view.  An option to set default view would be super.

Thank you.  Love this plugin!
-Kevin

**Comment by pR0Ps** [comment]
The ability to set a default layer was added in #13 and has been released in v2.1.0 (that update is currently [awaiting approval](https://github.com/grafana/grafana-plugin-repository/pull/642) by the Grafana team). Feel free to reopen if I've misunderstood!
