### ISSUE TITLE
Crashing in Grafana 7.0

### ISSUE THREAD

**Issue by KevinUrbanski** [pR0Ps/grafana-trackmap-panel#32]
Hello there.

I've upgraded to Grafana 7.0 and am seeing an error screen pop up saying An unexpected error happened, TypeError: Cannot read property '0' of undefined. This comes up when building my InfluxDB query.  The remaining text of the error message is below.
```
    in t
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in Ma
    in div
    in on
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

**Comment by Kimmax** [comment]
Ran into the same issue. Build the query first, then change the visualization to TrackMap. Lat goes into query A.

**Comment by KevinUrbanski** [comment]
Great. Thank you Kim.

**Comment by tinglis1** [comment]
I have been unable to transfer my TrackMap to v7.1.1.

I have a query and map that is working fine on v6.7.4 but no matter what I try I cannot get it to function on v7. I ahve tried the steps suggested above.

`SELECT mean("latitude") as "lat", mean("longitude") as "lon" FROM "state" WHERE ("domain" = 'person' AND "entity_id" = 'tim') AND $timeFilter GROUP BY time($__interval) fill(none)`

When i use the query in v7 it loads the data into a table fine. I save it and then try converting to TrackMap but it throws the following error.

`An unexpected error happened
Details
TypeError: Cannot read property 'emit' of undefined
    in t
    in x
    in Qr
    in div
    in div
    in t
    in t
    in div
    in Wa
    in div
    in div
    in uo
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l`

**Comment by pR0Ps** [comment]
I think this has something to do with the switch to React and/or the [new plugin architecture of v7](https://grafana.com/blog/2020/05/18/grafana-v7.0-released-new-plugin-architecture-visualizations-transformations-native-trace-support-and-more). As far as I can tell, the breakage is happening right after my plugin loads and calls `super` in the constructor so I'm not really sure what I could be doing wrong.

I've been meaning to refactor the plugin into using their recommended stack (React components + TS + their new plugin tooling) but haven't gotten around to it. I can't really give a timeline on what that'll be done. At this point maybe just avoid v7.0 if you really depend on this plugin, sorry.

If you find any hacks to just "make it work" in the meantime, send them my way and I'll apply them.

**Comment by xkilian** [comment]
I have not tested this, but this could this be a valid fix?
[Fork that seems to let on a fix for Grafana 7.x](https://github.com/nlubello/grafana-trackmap-panel/commit/df9dbd0bb60e03ab9aac7b811cc0c7eb51a5a189)

**Comment by pR0Ps** [comment]
I just tested it locally and it didn't seem to fix anything. I've made a comment on that commit asking for clarification.
