### ISSUE TITLE
Plugin not working in Grafana snapshot

### ISSUE THREAD

**Issue by MatinF** [pR0Ps/grafana-trackmap-panel#35]
Hi there,

I'm trying to use the plugin as part of my Grafana dashboard. However, when I try to create a snapshot, the plugin returns an error - is this a general issue or specific to this plugin?

![image](https://user-images.githubusercontent.com/26184427/89891555-930f6c80-dbd5-11ea-8eaf-9434e68cc7d6.png)

best,
Martin

**Comment by pR0Ps** [comment]
I can't reproduce here (snapshots work fine for me) so I'm assuming it's an installation issue.

For self-hosted instances, like @GeoffreyJohnen said, running `grafana-cli plugins install pr0ps-trackmap-panel` as the grafana user and restarting the grafana service should fix it.

I've never used the cloud account thing you referenced so you may have to check the documentation for that service to see if there's anything special you have to do to install plugins for it.
