### ISSUE TITLE
Hover over for details

### ISSUE THREAD

**Issue by viktak** [pR0Ps/grafana-trackmap-panel#36]
I was wondering if it is possible to configure the map in a way that when the mouse hovers over a track point, it shows the details (or at least the time stamp) of that point, like any other graph in Grafana does, i.e.:
![grafana-hover-over-example](https://user-images.githubusercontent.com/12509879/90398261-ca808c00-e0a1-11ea-9e60-6b12729e41e9.png)

If it is not possible, please take this as a feature request :)

Thank you!

**Comment by pR0Ps** [comment]
It's definitely possible, I just haven't implemented it. See #18
