### ISSUE TITLE
Multiple point/tracks

### ISSUE THREAD

**Issue by MrBoggi** [pR0Ps/grafana-trackmap-panel#38]
Hi

I’m trying to use the TrackMap to plot some data. I use InfluxDB to store data and my data is stored as follows:
measurement: geodata
Fields: latitude, longitude
Tags: DevEUI (This is a MAC address of the sensor sending lat and long).

I would like to plot each sensor based on the DevEUI but I cannot seem to get the query correct.
If I use the following query, I get all sensors plotted as one:
`SELECT "latitude", "longitude" FROM "geodata" WHERE time >= now() - 12h`

If I add a group by DevEUI, I get nothing in the map:
`SELECT "latitude", "longitude" FROM "geodata" WHERE time >= now() - 12h GROUP BY "DevEUI"`

Anyone got any good hints as to what I’m doing wrong?

I was hoping not to make one query pr DevEUI since I do not know when new ones are added and so on.

**Comment by pR0Ps** [comment]
Sorry, showing data in multiple tracks isn't currently implemented. See #4
