### ISSUE TITLE
Document zooming with scroll wheel

### ISSUE THREAD

**Issue by Sjorsa** [pR0Ps/grafana-trackmap-panel#41]
Currently, you can't zoom using the scroll wheel, only with the + and - buttons. This would be a good QOL feature.

**Comment by DmitrySidorow** [comment]
"scrollWheelZoom": true 
in panel JSON

**Comment by Sjorsa** [comment]
Aha, thanks!

**Comment by pR0Ps** [comment]
Reopening as a reminder to document this in the readme
