### ISSUE TITLE
Types in query?

### ISSUE THREAD

**Issue by DrMichael** [pR0Ps/grafana-trackmap-panel#42]
Sorry, I could not find any doc about that...

I saw in examples, that you can set types for data points. How can that be done? I tried:

```
SELECT
  to_timestamp(floor((extract('epoch' FROM date) / 60)) * 60) AT TIME ZONE 'UTC' as time_sec,
 avg(latitude) AS lat,
 avg(longitude) AS lng,
 0 as type,
 null as address
FROM
  positions
WHERE
  $__timeFilter(date)
GROUP BY 1
ORDER BY 1 AS
```
and formatted as table, but that does not work. Formatting as timeseries works with:
```
SELECT
  to_timestamp(floor((extract('epoch' FROM date) / 60)) * 60) AT TIME ZONE 'UTC' as time,
	avg(latitude) AS lat,
	avg(longitude) AS lng
FROM
  positions
WHERE
  $__timeFilter(date)
GROUP BY 1
ORDER BY 1 ASC
```

**Comment by bassmaster187** [comment]
This feature is in a fork of trackmappanel used by Teslalogger: https://github.com/bassmaster187/TeslaLogger

![image](https://user-images.githubusercontent.com/6816385/96466727-6fe2e800-122a-11eb-9135-cdd1aed0d1b5.png)

**Comment by DrMichael** [comment]
Ah. Which fork is it?

(Great piece of software, TeslaLogger:-)

**Comment by bassmaster187** [comment]
If there is a need besides Teslalogger and Teslamate, someone have to make a config panel for the different types of icons. Actually it's hard coded for my need.

**Comment by pR0Ps** [comment]
Closing since the feature mentioned is not part of this project.
