### ISSUE TITLE
Can't find ...

### ISSUE THREAD

**Issue by dirk-ecker** [pR0Ps/grafana-trackmap-panel#45]
implementation for 

- Places a dot on the map at the current time as you mouse over other panels.
- Multiple map backgrounds: OpenStreetMap, OpenTopoMap, and Satellite imagery.

Can you tell me how this is done?

**Comment by pR0Ps** [comment]
There are some screenshots in the readme. The top one shows hovering over data in another panel and a dot appearing on the map. The third one shows the map picker in the top right. These are both features that are enabled by default so if you don't see them, something has gone wrong. The map picker can be disabled in the settings so make sure that setting isn't enabled if you don't see it.

You'll need to be a little more specific if that's not what you were asking.

**Comment by dirk-ecker** [comment]
No that is exactly the point. I saw the screenshots but could not find the corresponding part in the source. Also the settings seems to have no map picker entry. I am on master branch, is that the problem?

Yes it seems to be. 39 Commits behind.

Okay, now I understand.
