### ISSUE TITLE
Changing default map

### ISSUE THREAD

**Issue by jakobdalsgaard** [pR0Ps/grafana-trackmap-panel#47]
I tried changing the default map by editing this line:

https://github.com/pR0Ps/grafana-trackmap-panel/blob/b395938867243d08ac6382987a7e8fb3cee6c797/src/trackmap_ctrl.js#L26

However, the default did not change. Some debugging showed that the default written in line 26 is not what is returned later, in line 209.

https://github.com/pR0Ps/grafana-trackmap-panel/blob/b395938867243d08ac6382987a7e8fb3cee6c797/src/trackmap_ctrl.js#L209

Is this intentional?

**Comment by pR0Ps** [comment]
I just tried this and I can't reproduce. The default layer is just the key to index the `this.layers` object with. Changing it and rebuilding should change the layer that is set as the default. Note that this only defines the defaults for the panel so if you've explicitly set an option then it's not going to change anything. Try adding a new panel and check which map it uses.
