### ISSUE TITLE
Route crossing the dateline

### ISSUE THREAD

**Issue by DBREngineer** [pR0Ps/grafana-trackmap-panel#48]
Hello,
I have a route that crosses the dateline. The plugin draws a line across the screen. Is there any way to prevent this?

Thanks for your support!
![grafik](https://user-images.githubusercontent.com/39679207/107649565-ded2c980-6c7d-11eb-9843-313dbf504466.png)

**Comment by pR0Ps** [comment]
This is due to how Leaflet (the map rendering library) works. It may be able to be worked around in the plugin by drawing 2 lines as detailed here: https://stackoverflow.com/a/65870755
