### ISSUE TITLE
cannot display data on dashboard

### ISSUE THREAD

**Issue by nanaromance** [pR0Ps/grafana-trackmap-panel#5]
HI i follow your instruction  but cannot display the data from influxdb to the dashboard.

> location,geohash=w4rqqb1,host=server1,latitude=13.756194,longitude=100.494154

is this correct?

**Comment by nanaromance** [comment]
![trackmap](https://user-images.githubusercontent.com/29445032/41284438-7bd794de-6e63-11e8-82ef-a7d38c4f93d9.png)

**Comment by pR0Ps** [comment]
That's the exact setup I have (which is displaying data normally)

![screen shot 2018-06-13 at 8 55 30 pm](https://user-images.githubusercontent.com/466941/41385851-2c21bce6-6f4c-11e8-91a1-5001a4bc16cc.png)

There are a few options:
1. Your database is set up a bit differently. I have the database configured in Grafana, a "location" measurement on it, and "latitude" and "longitude" keys within that. Try running a query like `SELECT * FROM "<database>"."autogen"."location" LIMIT 10` to see if you see latitude and longitude fields.
2. There is data being returned, but it's not in the expected format. There might be some errors in the JS console when loading the page. Are the values integers?
3. There's just no data for the date range you're testing. When there's no data the panel defaults to displaying the world map.

**Comment by nanaromance** [comment]
Thank you for your information.

I'm solve with add lat,lon to field key in influxdb
