### ISSUE TITLE
No dot on the map

### ISSUE THREAD

**Issue by nonujigu** [pR0Ps/grafana-trackmap-panel#50]
Trackmap works as expected with one exception: When I hover over another widget, there is no dot visible on the Trackmap widget.

Environment:

Grafana version: 7.4.1
Data source type & version: postgres 11 + TimescaleDB
OS Grafana is installed on: CentOS 7
User OS & Browser: windows 10 + chrome, firefox (doesn't matter)
Grafana plugins: Worldmap panel, TrackMap

**Comment by feheragoston** [comment]
I have the same symptoms, the hover dot stopped working for me after grafana was updated to 7.4.0. Upgrading the plugin to the latest and Grafana to the latest 7.4.1 didn't fix the issue. After downgrading Grafana to v7.3.7 (1e261642f4) it works again.

**Comment by nonujigu** [comment]
> I have the same symptoms, the hover dot stopped working for me after grafana was updated to 7.4.0. Upgrading the plugin to the latest and Grafana to the latest 7.4.1 didn't fix the issue. After downgrading Grafana to v7.3.7 (1e261642f4) it works again.

Thanks for the hint with the downgrade. I downgraded Grafana to v7.3.7 and I can confirm that it works with this version.

**Comment by CptHolzschnauz** [comment]
Same here..

**Comment by skiminokf** [comment]
> I have the same symptoms, the hover dot stopped working for me after grafana was updated to 7.4.0. Upgrading the plugin to the latest and Grafana to the latest 7.4.1 didn't fix the issue. After downgrading Grafana to v7.3.7 (1e261642f4) it works again.

Thank you very much for the solution!!!

**Comment by CptHolzschnauz** [comment]
But downgrading is not a solution. I think it an  easy one for the maintainer. Hopefully he reads this issue topic.
Anyway thanks a lot for this plugin. And check the pull requests...

**Comment by ampjunkie** [comment]
Grafana 7.4.2 is now released. Can someone test to see if this fixes it?

**Comment by skiminokf** [comment]
> Grafana 7.4.2 is now released. Can someone test to see if this fixes it?

I've checked it, still not working.

**Comment by ampjunkie** [comment]
> > Grafana 7.4.2 is now released. Can someone test to see if this fixes it?
> 
> I've checked it, still not working.

Thanks for checking. Hopefully the maintainer can look at it and provide a fix.  It's a great plugin.

**Comment by pR0Ps** [comment]
Fixed by #51

**Comment by N3v3R3nD** [comment]
After updating it does not work at all for me I just get Error loading: pr0ps-trackmap-panel on both 7.3.7 and 7.4.2.
Anyone else with the same issue?

**Comment by pR0Ps** [comment]
@N3v3R3nD Are there any error messages in the console?

**Comment by N3v3R3nD** [comment]
@pR0Ps The only error I see is:
Error loading: pr0ps-trackmap-panel
I just replaced the trackmap_ctrl.js with the new and restarted Grafana then tried in the different versions. 
How can I get you more info?

**Comment by ampjunkie** [comment]
In grafana in home assistant, I can only install plugins via a config file which then installs from here: https://grafana.com/api/plugins/pr0ps-trackmap-panel/versions/2.1.0/download
I downloaded manually and see that trackmap_ctrl.js is from June 2020.  Can you help update on grafana? Thanks!

**Comment by skiminokf** [comment]
> Fixed by #51 ([4d258a5](https://github.com/pR0Ps/grafana-trackmap-panel/commit/4d258a58ce8a72ed5def08cc685f6606c15223ce))

Good day pR0Ps, thank you for an excelent plugin!!!

I have just checked out your master brunch with a fix. 
Compiled it with:
npm install
npm run build

And restarted the grafana.

Plugin is working, but the cursor is still not showing on the map.

**Comment by skiminokf** [comment]
Update here.

Reinstalled the Grafana and plugin is working now!

Thank you very much for a fast response.

**Comment by pR0Ps** [comment]
@ampjunkie I will push an update soon - just want to take care of one other issue first.

**Comment by ampjunkie** [comment]
> @ampjunkie I will push an update soon - just want to take care of one other issue first.

Thanks very much for your prompt fix and reply.   Teslamate also uses it, so I hope they pick up the fix.  As I said earlier, it's a great plugin!

**Comment by rodri16** [comment]
Still problemwith dots on grafana v9.3.6 and Trackmap v2.1.4
