### ISSUE TITLE
V2.1.2 - When will it be available on Grafana?

### ISSUE THREAD

**Issue by pbegg** [pR0Ps/grafana-trackmap-panel#52]
Hello,

I see you have created an update to support Grafana 7.x.x.

I can still only see your v2.1.0 available on the grafana plugin list, when will v2.1.1 be available?

**Comment by pR0Ps** [comment]
Whenever https://github.com/grafana/grafana-plugin-repository/pull/878 is merged by the Grafana team

**Comment by pbegg** [comment]
Thanks for a great plugin!!

**Comment by pR0Ps** [comment]
Will close this once the plugin is released on grafana.com

**Comment by MatinF** [comment]
Any updates on the ETA for this?

**Comment by pR0Ps** [comment]
Nope. You can follow the PR linked above for more info.

**Comment by pR0Ps** [comment]
v2.1.2 has been released to the Grafana plugin repository
