### ISSUE TITLE
Auto Zoom (too much zoom)

### ISSUE THREAD

**Issue by cdaher78** [pR0Ps/grafana-trackmap-panel#56]
At first, congrats for this fine work.

I'm using this plugin to plot some outdoor devices postion with a serial GPS attached, but the autozoom function zooms a lot and if I disable it I lose the centered position on the map. 

Is there a way to set less zoom and keep it centralized? I also notice that I can't select satellite view with auto zoom. When I zoom out two times it's possible but it returns to the position where I can't see where the device is.

Thanks in advance.

**Comment by alduxvm** [comment]
I'm facing the same issue, in my case I stop seeing the openstreet satellite tiles... I think it has to do with the maxZoom in the satellite (https://github.com/pR0Ps/grafana-trackmap-panel/blob/master/src/trackmap_ctrl.js line 65), if that zoom is changed to 23-25, the tiles will not be gray, I'm running docker and I installed the plugin with the cli, so I do not know how to modify it unless is changed in the repo code...

**Comment by guanucoluis** [comment]
Hello, I have a similar problem. I try to disable "auto-zoom" in configuration panel. When I save changes the  "auto-zoom"  still enable.  Are you things that this "issue" requiest a new ticket? 
Thanks for any informations!

**Comment by CptHolzschnauz** [comment]
This is no bug, the idea is that all data points delivered are visible.
You can code any behaviour you want based on the leaflet lib, IMHO this issue can be closed.

**Comment by pR0Ps** [comment]
Fixed by using `maxNativeZoom` in the tile layers - should now zoom in to any amount by scaling up the most detailed image
