### ISSUE TITLE
Unsigned plugin

### ISSUE THREAD

**Issue by siredmar** [pR0Ps/grafana-trackmap-panel#58]
Hi!
Would you mind signing your plugin?
Here is a link for information on how to do it: https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/

![image](https://user-images.githubusercontent.com/2737320/111293333-747cc280-8649-11eb-88eb-775d10baab22.png)

Cheers,
Armin

**Comment by siredmar** [comment]
I just noticed, that your github action released 6 days ago should sign the plugin. Problem is, that i cannot install the latest release `2.1.2` (that is signed) via plugin list in grafana.

**Comment by pR0Ps** [comment]
The previous release was not signed but the latest one is. Just waiting for Grafana to update it. See #52
