### ISSUE TITLE
OpenSeaMap functionality

### ISSUE THREAD

**Issue by JoseJor** [pR0Ps/grafana-trackmap-panel#66]
Hi,
I was wondering if it is possible to connect the functionality of "Open Sea Map"(https://map.openseamap.org/) on Track Map. What I am interested on is the sea marks.

I use Track Map to plot the position of vessels, and expanding the functionality with sea marks would be very useful.

Regards, Jose

**Comment by KEGustafsson** [comment]
@JoseJor Here are couple of examples with sea marks as an overlay.
[OpenStreetMap with Seamarks](https://github.com/KEGustafsson/grafana-trackmap-panel/blob/marine/src/trackmap_ctrl.js#L171-L176)
[OpenTopoMap with Seamarks](https://github.com/KEGustafsson/grafana-trackmap-panel/blob/marine/src/trackmap_ctrl.js#L181-L186)
You can add these directly to your `trackmap_ctrl.js` file and start to use those right away.

**Comment by pR0Ps** [comment]
Implemented in df95bcda9c607a6c3ff562cf7014a1ccf7483d9a
