### ISSUE TITLE
default layer option not showing

### ISSUE THREAD

**Issue by Frazzer951** [pR0Ps/grafana-trackmap-panel#71]
I saw in Pull request #13 that an option of a defualt layer was added and merged. I do not see this option when I go to configure the panel. 
This is what I see.
![image](https://user-images.githubusercontent.com/23227655/142680278-39144ad2-cfc4-4561-aaed-d8f2648ec87b.png)

Am I doing something wrong? Grafana says I have version 2.1.2 installed which is the latest version.

**Comment by pR0Ps** [comment]
Fixed by #64
