### ISSUE TITLE
Missing Signature

### ISSUE THREAD

**Issue by ball-hayden** [pR0Ps/grafana-trackmap-panel#72]
![Screenshot 2022-03-14 at 16 16 47](https://user-images.githubusercontent.com/1596233/158215028-df8f2ccc-d288-4b31-803a-85ec3a941bfb.png)

Under Grafana 8.4.2 the plugin is complaining it is unsigned again

**Comment by fencer** [comment]
Getting the same issue here

**Comment by pR0Ps** [comment]
No idea why that was happening but v2.1.3 was just released here: https://github.com/pR0Ps/grafana-trackmap-panel/releases/tag/v2.1.3 and it's signed properly
