### ISSUE TITLE
add cyclist map from openstreetmap to pr0ps-trackmap-panel plugin

### ISSUE THREAD

**Issue by mirzafaraz82** [pR0Ps/grafana-trackmap-panel#73]
Hello all,
I would really appreciate if someone can show me how to add different maps (example: cyclist map) from OpenStreetMap on to this Trackmap  Panel. 
I would like to track a cyclist data on the TrackMap, which is working absolutely fine with "OpenStreetMap", "OpenToPoMap" and "Satellite" view. But my use case requires a seperate cyclist map available on  openstreetmap .

Thanks in advance.
@pR0Ps @olewales @aler9 
![cyclist map](https://user-images.githubusercontent.com/57925281/176389258-998ec143-5e6e-4475-a18d-00fd1faddc05.png)

**Comment by pR0Ps** [comment]
Implemented in df95bcda9c607a6c3ff562cf7014a1ccf7483d9a
