### ISSUE TITLE
This doesn't work with the newest Grafana version

### ISSUE THREAD

**Issue by woyteck1** [pR0Ps/grafana-trackmap-panel#74]
Any chance to fix it please?

**Comment by tormodvolden** [comment]
I also see that this TrackMap plugin doesn't work any longer with Grafana 9.0.7. I think I had checked quickly that it worked on 9.0.2 but I am not sure.

@woyteck1 What was your last working versions and the first broken?

**Comment by Okaho** [comment]
9.3.6, not worked, "Error loading: pr0ps-trackmap-panel".

**Comment by pR0Ps** [comment]
I'm not sure what's going on here, it's working fine for me
![Screen Shot 2023-02-17 at 12 26 55 AM](https://user-images.githubusercontent.com/466941/219557254-b3109da3-437b-4892-a71c-a20f1d88225e.png)

**Comment by Okaho** [comment]
installed from archive
![Screenshot_10](https://user-images.githubusercontent.com/48982482/219596196-6f8353af-88fc-45bb-a3f1-8ed3128b5e7b.png)

**Comment by Okaho** [comment]
Installation from https://grafana.com/api/plugins/pr0ps-trackmap-panel/versions/2.1.4/download helped.

**Comment by woyteck1** [comment]
This works for me in 1.27.2
