### ISSUE TITLE
Dot point not displayed in Map

### ISSUE THREAD

**Issue by sebfournier95** [pR0Ps/grafana-trackmap-panel#75]
Hello, 

One question, why dot point is not displayed in Map ? 

Here is the queries : 

![image](https://user-images.githubusercontent.com/62887360/180957854-27165685-7dea-46b5-85a3-c66ed4ceafcb.png)

Here is the result :

![image](https://user-images.githubusercontent.com/62887360/180958231-a223f0ea-3ed2-4f8a-8d40-84e6909f40cb.png)

**Comment by chaos-user** [comment]
Hi @sebfournier95 

Unfortunately this is an already identified and reported issue by some users.
Hope developers can fix this feature soon.

https://github.com/pR0Ps/grafana-trackmap-panel/issues/67

**Comment by sebfournier95** [comment]
Bonjour, 
      
      Je suis en congé jusqu'au 5 Septembre.
    En mon absence, vous pouvez contacter Malo Pocheau :
    
      ***@***.***
      +33 6 69 62  42 96
      
    
    -- 
Cordialement
Sébastien Fournier

Tel : +33 6 28 70 64 18
Skype : sebosdu95
Email : ***@***.***

**Comment by pR0Ps** [comment]
Fixed by #77 in v2.1.3
