### ISSUE TITLE
Feature isn't working

### ISSUE THREAD

**Issue by dyrschatten** [pR0Ps/grafana-trackmap-panel#78]
The feature:
- Places a dot on the map at the current time as you mouse over other panels
Is not working, as it's not placing a dot when moving over other panels

Grafana v9.3.2 (21c1d14e91)
TrackMap V2.1.4

**Comment by nhurman** [comment]
I had the same issue, and found that it doesn't work with the newer "timeseries" grafana view type. Flipping it to the (deprecated) graph view makes it work again.

Dashboard > Settings > JSON Model
```
      "type": "graph",
```

**Comment by umbm** [comment]
> Dashboard > Settings > JSON Model
> 
> ```
>       "type": "graph",
> ```

There are a lot of "type" tags. 
Whats the right one?

**Comment by dyrschatten** [comment]
As @nhurman said changing type from "timeseries" to "graph" makes it work again.

**Comment by Okaho** [comment]
@umbm , @dyrschatten how did you run version 9.3.2 with this plugin?

**Comment by Okaho** [comment]
i get the message in interface "Error loading: pr0ps-trackmap-panel".
аbout the selection of dots: I was helped by the graphs "Graph (old)" inherited from the old versions (v7.x), new versions "Time series" do not work.

**Comment by Okaho** [comment]
https://github.com/pR0Ps/grafana-trackmap-panel/issues/74#issuecomment-1436343492

**Comment by younesmaia** [comment]
Any way to display the dot on the LAST data point (without the need to hover over the currrent time)?
