### ISSUE TITLE
remove executable bit from files in installation package

### ISSUE THREAD

**Issue by sivu** [pR0Ps/grafana-trackmap-panel#82]
Installation package contains many files that have incorrectly executable bit (+x) set. This causes grafana to refuse access to plugin.

For example:

`EROR Plugin file access forbidden             logger=context userId=1 orgId=1 uname=admin error="access is forbidden to executable plugin file /var/lib/grafana/plugins/pr0ps-trackmap-panel/module.js" remote_addr=x

EROR Plugin file access forbidden             logger=context userId=1 orgId=1 uname=admin error="access is forbidden to executable plugin file /var/lib/grafana/plugins/pr0ps-trackmap-panel/img/logo.svg" remote_addr=x`

**Comment by pR0Ps** [comment]
I just checked [the zip from the latest release](https://github.com/pR0Ps/grafana-trackmap-panel/releases/download/v2.1.4/pr0ps-trackmap-panel-2.1.4.zip) as well as the one from [the grafana plugin page](https://grafana.com/grafana/plugins/pr0ps-trackmap-panel/?tab=installation) and neither of them have the executable bits set on any of the files. Is it possible that your files got written to a filesystem that messed up the permissions on them at some point?
