### ISSUE TITLE
No dot on the map #50

### ISSUE THREAD

**Issue by rodri16** [pR0Ps/grafana-trackmap-panel#83]
No dots using Grafana v9.3.6 and Trackmap v2.1.4

**Comment by yugako** [comment]
The same for me with Grafana v9.4.7

**Comment by TZECHIN6** [comment]
The document only mention it takes "lat" and "long" as Time series data, so.... how about the dot?

**Comment by pR0Ps** [comment]
The dot is rendered based on the currently hovered data point as seen in this screenshot: https://github.com/pR0Ps/grafana-trackmap-panel/blob/master/src/img/topo-crosshair.jpg

My suspicion as to why it's not showing up in newer Grafana versions is that this plugin was built using Angular and Grafana has moved on to React (see #84). They have shims in place, but I guess they're not perfect.

**Comment by rodri16** [comment]
It is possible to migrate from Angular to React but don't know how much work does it implies to you @pR0Ps 
[Migrate from AngularJS to React](https://grafana.com/developers/plugin-tools/migration-guides/migrate-angularjs-to-react)
