### ISSUE TITLE
Angular is deprecated - please migrate to React

### ISSUE THREAD

**Issue by tolzhabayev** [pR0Ps/grafana-trackmap-panel#84]
# Hello :wave: from Grafana Labs

We have detected that your plugin might still be using `AngularJS` and recommend migrating it to `React`, so that it may continue to operate successfully in future versions of Grafana.

You can read more on why and how by visiting our documentation: https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

You can reach out to us with any questions via slack: [slack.grafana.com](https://slack.grafana.com) - channel `#plugins` or our [plugin development community forum](https://community.grafana.com/c/plugin-development/30)

**Comment by CptHolzschnauz** [comment]
Hello pROBs et all

Now with Grafana 10.3.4 they added  annoying warning shield on all Angular based Grafana Panels, so i had to downgrade because there is no easy config to turn off these warnings.

Anyway, the urge for a migration to React becomes greater, with Grafana 11 all Angular Panels will be kicked out.

The question is if there is a contributors base here for that task. For my part, I did a branch of the plugin for my needs based on trackmap-panel  and can help with leaflet/mapbox stuff but know not much of the Grafana Plugin/React functionality.

What about pROPs? Others?

It's such a cool plugin it would be a shame if it's just slowly fading out.
It would be cool to kick off a major release development for the React requirement.
Kind regards
Your Captain

**Comment by younesmaia** [comment]
@CptHolzschnauz 
There is an easy way to get rid of the warnings. No downgrade needed:

Just edit your Grafana's default.ini file located at /grafana/conf/
Around line 1600 you'll see the item "hide_angular_deprecation". 
Add your plugin names separated by commas there. If you do it for all affected plugins, all warnings will be gone.

`hide_angular_deprecation = pr0ps-trackmap-panel`

Too bad this is not stated anywhere. Took me a while to find it!

**Comment by CptHolzschnauz** [comment]
@younesmaia 
I found it meanwhile, you can disable those warnings completely by adding the following to your config.ini file:

[feature_toggles]  
angularDeprecationUI = false

Alternatively, you can disable the warnings only for some plugins as you mentioned with:

[plugins]
hide_angular_deprecation = pr0ps-trackmap-panel

BTW: I agree, add such a warning by surprise without a statement how to remove was not really user-friendly. All the End-Users asked "What is Angular? A virus or a hacker?"

**Comment by anthosz** [comment]
Due to the fact this plug-in seems not maintained anymore, probably geomap (nativaly supported by Grafana) can replace it with the route feature 🤔

**Comment by CptHolzschnauz** [comment]
The killer feature is the function that when you mouseover a timeseries it shows the point on the map when/what. I will check out the geomap, maybe there is a way. Or i stay with grafana 10 because I don't like to change/recode a perfect running system like pROBs panel.

**Comment by StelioKontos21** [comment]
> The killer feature is the function that when you mouseover a timeseries it shows the point on the map when/what. I will check out the geomap, maybe there is a way. Or i stay with grafana 10 because I don't like to change/recode a perfect running system like pROBs panel.

Did you manage to find a way with route feature? I think it is not ready yet to get the funcionality of pR0Ps plugin. 

![image](https://github.com/pR0Ps/grafana-trackmap-panel/assets/167177955/8da96262-e530-432e-9355-808dfa140f5c)

This is the closest thing I manage to do. If you have a panel with a measure, you can colour the points based on a threshold. Still, won't mark the exact point when hovering over the timeseriespanel.

**Comment by CptHolzschnauz** [comment]
> Did you manage to find a way with route feature? I think it is not ready yet to get the funcionality of pR0Ps plugin.
No, I'll stay with Grafana 10 and my plugin branch from pROBs Angular map panel, it fullfils all my needs exept for the text wrap issue in the Table plugin. My gutfeel says don't touch that running system.
