### ISSUE TITLE
POINTER DOESNT WORK

### ISSUE THREAD

**Issue by ignamendi21** [pR0Ps/grafana-trackmap-panel#87]
Hello : ),
I manged to connect it to my influxd and I can see the track:
THIS WORKS:

from(bucket: "ANDROMAXA")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) => r["_measurement"] == "navigation.position")
|> filter(fn: (r) => r["source"] == "Navi.1")
|> filter(fn: (r) => r["_field"] == "lat" or r["_field"] == "lon")
|> aggregateWindow(every: v.windowPeriod, fn: median)
|> yield(name: "median")

HOWEVER, THE POINTER NOT. I  hover over another timeserie but the pointer is not appearing and not moving through the track.. Anyone knows why?

**Comment by mukeshkb4u** [comment]
Hi. 

This still doesnt seems to work on ver3.0.0.
I am able to get the track but the Map pointer is not appearing while hovering over another timeseries panel.
Not sure if i am missing anything.

**Comment by pR0Ps** [comment]
Do you have the shared crosshair enabled for the dashboard? https://community.grafana.com/t/grafana-tooltip-customization/66221/7

This is something I explicitly tested and made sure was working for [both legacy and current hover events](https://github.com/pR0Ps/grafana-trackmap-panel/blob/e3a776c2a2ba5bc193e135f1d1cf586be38dcfe0/src/TrackMapPanel.tsx#L451-L452) so I don't know why it wouldn't be working.
