### ISSUE TITLE
Compatiblity Issue w/ Grafana v6

### ISSUE THREAD

**Issue by lephisto** [pR0Ps/grafana-trackmap-panel#9]
Hi there,

since updating to Grafana 6 the Panel is not rendering anymore. This might be due migration of Grafana to React. I tried to track the error down, but did not succeed. Sometimes resizing the Panel makes it load.

**Comment by pR0Ps** [comment]
@lephisto Thanks for reporting this, it should be fixed now. Feel free to reopen if you're still seeing it in v2.0.4+

**Comment by jonasdig** [comment]
I have the same problem with v2.0.4 on Grafana 6.2.5.
