### ISSUE TITLE
3.0.0 Getting included in Grafana Cloud

### ISSUE THREAD

**Issue by philbegg** [pR0Ps/grafana-trackmap-panel#91]
Is there an intention to get this new version included with Grafana Cloud so it can be installed on a hosted instance?

**Comment by rodri16** [comment]
The plugin has been removed from Grafana's catalog
![deprecated](https://github.com/pR0Ps/grafana-trackmap-panel/assets/7334666/60963828-622c-4028-b946-3f8245b638ec)

**Comment by pR0Ps** [comment]
Yes,  I currently have a support ticket open to reinstate the plugin in the catalog.

**Comment by philbegg** [comment]
Is there anywhere we can follow the progress for having it added back to the catalogue?

**Comment by pR0Ps** [comment]
@philbegg I don't think so, sorry. I've been having issues getting it reinstated. I've opened 2 supports tickets so far, both of which have had someone say they will forward it to the plugin team and not respond further.

I've just attempted to follow up again.

If anyone has any contacts at Grafana that might be able to help, I'd appreciate if you could put them in contact with me.

**Comment by pR0Ps** [comment]
The plugin has been un-deprecated and the update should go live soon - will close this issue once it's available.

**Comment by philbegg** [comment]
That's great news - thanks a lot for your efforts.

**Comment by powerbill** [comment]
Is there anything we can do to help motivate Grafana to get the 3.x plugin available?

**Comment by pR0Ps** [comment]
There are some issues they brought up while reviewing that I need to fix, #89 being one of them

**Comment by pbegg** [comment]
Hello, I have some contact with Grafana through our paid Grafana Cloud instance, which might help to push things along if needed. Is #89 still an outstanding issue that needs to be addressed?

**Comment by pR0Ps** [comment]
Yes, sorry, #89 needs to be addressed before v3.x is approved and I haven't gotten around to fixing it yet.

**Comment by NoPlayBack** [comment]
I thought, even if this new version is not available through Grafana Cloud, i would be able to install that myself by extracting and putting it into the grafana plugin folder, but that didn't work.
Am i doing something wrong, or is it not possible to install manually ?

**Comment by zolbarna** [comment]
I was able to copy this version to the plugins folder, and it's works perfectly. I was using it via docker, and with one of the latest grafana.

Don't remember if any special action has been taken.

**Comment by NoPlayBack** [comment]
using Grafana 11.1.3 on a rasperrypi.... no change in default config so pluginfolder is /var/lib/grafana/plugins
I download this zip here and create "/var/lib/grafana/plugins/pr0ps-trackmap-panel" with content img-folder, module.js, module.js.map, plugin.json...... and so on.
I do also stop and start grafana-server.service.
After that i go to an existing panel, try to add a visualization, and then i search the visualizations list for "TrackMap".
Am i doing something wrong here ?????

**Comment by zolbarna** [comment]
What I've done right now: 
-Started with a clean ubuntu24.04 install
-Installed grafana with a official way
-created a /var/lib/grafana/plugins folder
-extracted the pr0ps-trackmap-panel into the plugin folder
-chown grafana:grafana /var/lib/grafana/plugins -r
-restart the service 

![image](https://github.com/user-attachments/assets/c09f2d67-314b-4bf8-afff-13d8ed8746cb)

**Comment by NoPlayBack** [comment]
ok.... what i did now is adding a visualization to an existing panel, then choosing the visualization be using the drop down menu on top right side of the window... there is did not show up. But then i did type "map" in the search for window and there it is. Now i see it also when simply opening the drop down, and now i also see it in the list of isntalled plugins.
No idea what happend...

**Comment by zolbarna** [comment]
Glad it works ;)

**Comment by philbegg** [comment]
Hello, now that this has been updated can we please send it to Grafana to be inlcluded?

**Comment by pR0Ps** [comment]
Sorry, I keep dropping the ball on this. The reviewer requested a few more minor changes. Just made them now, pushed a new version, and resubmitted.

**Comment by pR0Ps** [comment]
Phew, v3.0.2 been accepted and published in the plugin catalog. Closing this out.
